{
 "title": "RavenDB Sample Data",
 "time": { "from": "2021-11-17T16:56:28.158Z", "to": "2022-02-17T09:45:12.697Z" },
 "templating": {
  "list": [
   { "name": "Limit", "query": "5,10,15" },
   {
    "name": "Product",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Product Rating ($Product)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "from index 'Product/Rating'\nwhere Name = \"${Product}\"\nselect Rating"
    }
   ]
  },
  {
   "title": "Daily Product Views",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "queryText": "from 'Products'\nwhere id() == 'products/77-A'\nselect timeseries(from 'INC:Views' between $timeFilter group by $__interval select sum())"
    }
   ]
  },
  {
   "title": "Suppliers",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "queryText": "from Suppliers where Address.Location != null select Name, Address.Location.Latitude as Latitude, Address.Location.Longitude as Longitude"
    }
   ]
  },
  {
   "title": "Top ${Limit} Countries in Orders",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "from \"Orders\" \ngroup by ShipTo.Country \norder by Orders_Count as long desc \nselect count() as Orders_Count, key() as Label\nlimit ${Limit}"
    }
   ]
  },
  {
   "title": "Employees",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "queryText": "from Employees select LastName, FirstName, Title, Address"
    }
   ]
  },
  {
   "title": "Top ${Limit} Companies",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "queryText": "from index 'Orders/ByCompany' as o\norder by Total as double desc \nload o.Company as c\nselect c.Name, Total\nlimit ${Limit}"
    }
   ]
  }
 ]
}